### ISSUE TITLE
[DISCUSSION] Resource linking failed during Android Studio build

### ISSUE THREAD

**Issue by dercodeling** [LawnchairLauncher/lawnicons#1044]
### About this discussion

I tried building Lawnicons from my fully up-to-date fork but it failed with an exception. The drawables it's looking for (referenced in lines 4-23 of `grayscale_icon_map.xml`) are indeed not located in res/drawable anymore, but so are all the other drawables in `grayscale_icon_map.xml`? Is this a known issue during the transition to the new icon system or is there something I can do to fix it? If there is any more information you need in order to be able to understand this behaviour I'll be happy to provide it.

The exact output is as follows:
`Execution failed for task ':app:processAppDebugResources'.
> A failure occurred while executing com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask$TaskAction
   > Android resource linking failed
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:4: error: resource drawable/aliucord_installer (aka app.lawnchair.lawnicons:drawable/aliucord_installer) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:5: error: resource drawable/animiru (aka app.lawnchair.lawnicons:drawable/animiru) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:6: error: resource drawable/bitrix24 (aka app.lawnchair.lawnicons:drawable/bitrix24) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:7: error: resource drawable/camera (aka app.lawnchair.lawnicons:drawable/camera) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:8: error: resource drawable/camera_date_folders (aka app.lawnchair.lawnicons:drawable/camera_date_folders) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:9: error: resource drawable/coinvero (aka app.lawnchair.lawnicons:drawable/coinvero) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:10: error: resource drawable/combined (aka app.lawnchair.lawnicons:drawable/combined) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:11: error: resource drawable/coolapk (aka app.lawnchair.lawnicons:drawable/coolapk) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:12: error: resource drawable/dialer (aka app.lawnchair.lawnicons:drawable/dialer) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:13: error: resource drawable/duelyst (aka app.lawnchair.lawnicons:drawable/duelyst) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:14: error: resource drawable/eksi_sozluk (aka app.lawnchair.lawnicons:drawable/eksi_sozluk) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:15: error: resource drawable/erste_hilfe (aka app.lawnchair.lawnicons:drawable/erste_hilfe) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:16: error: resource drawable/files (aka app.lawnchair.lawnicons:drawable/files) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:17: error: resource drawable/fix_price (aka app.lawnchair.lawnicons:drawable/fix_price) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:18: error: resource drawable/fxxxs_given (aka app.lawnchair.lawnicons:drawable/fxxxs_given) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:19: error: resource drawable/goodline (aka app.lawnchair.lawnicons:drawable/goodline) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:20: error: resource drawable/gramotnee (aka app.lawnchair.lawnicons:drawable/gramotnee) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:21: error: resource drawable/grill_one (aka app.lawnchair.lawnicons:drawable/grill_one) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:22: error: resource drawable/homeworker (aka app.lawnchair.lawnicons:drawable/homeworker) not found.
     app.lawnchair.lawnicons.app-main-59:/xml/grayscale_icon_map.xml:23: error: resource drawable/kinopoisk (aka app.lawnchair.lawnicons:drawable/kinopoisk) not found.`

**Comment by dercodeling** [comment]
Ok so I tried removing one of the problematic lines in `grayscale_icon_map.xml` and adding the corresponding line in `appfilter.xml` and the error for that line disappeared. A new error appeared for line 24 though (previously the last line mentioned in the error message was 23), so I assume all lines in `grayscale_icon_map.xml` are effected and causing this error, but only 20 of them are shown.

**Comment by dercodeling** [comment]
As there is unchanged activity here I assume no one else is having this problem, does anyone know why this (having these resources mentioned in `grayscale_icon_map.xml` but not actually located in `res/drawable`) is _not_ causing an error for you? It seems pretty logical to me, so I'm confused as to why this seemingly faulty code would run elsewhere (including, strangely, the Action `Build Debug APK` on this repo and on my fork). I tried reinstalling Android Studio and re-cloning the fork as well in the mean time, but that didn't change anything either. Any ideas would be greatly appreciated

**Comment by dercodeling** [comment]
I've temporarily solved the build error by commenting out all icon-tags inside `grayscale_icon_map.xml`.
It seems the missing drawables were removed in the process of switching to `appfilter.xml`, even though the respective lines weren't yet migrated from `grayscale_icon_map.xml`. They should be added to `appfilter.xml` now anyway, right? I know the needed information for one of the remaining lines of `grayscale_icon_map.xml` and I will add it at the end of this so somebody can add it, but I don't want to open any PRs myself until I am able to build properly again.

In doing that, I've run into a new problem, though, a `RuntimeException`, more specifically a `ClassNotFoundException`, which always occurs immediately after building when I try to open or apply Lawnicons. Obviously this could also be caused by whatever is causing the build error to be a problem for me, when it runs everywhere else regardless of the missing drawables. 
Once again, any ideas as to why either of these problems is occurring or why the build error is not occurring anywhere else would be greatly appreciated.

The log output for the latter exception is as follows:
```
E/AndroidRuntime: FATAL EXCEPTION: main
    Process: app.lawnchair.lawnicons, PID: 6605
    java.lang.RuntimeException: Unable to instantiate application app.lawnchair.lawnicons.LawniconsApplication package app.lawnchair.lawnicons: java.lang.ClassNotFoundException: Didn't find class "app.lawnchair.lawnicons.LawniconsApplication" on path: DexPathList[[zip file "/data/app/~~xWIHus-tAqgf2eC01b73sw==/app.lawnchair.lawnicons-YVk_ID21uazr0ylO68WanQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~xWIHus-tAqgf2eC01b73sw==/app.lawnchair.lawnicons-YVk_ID21uazr0ylO68WanQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1513)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1437)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7161)
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loopOnce(Looper.java:240)
        at android.os.Looper.loop(Looper.java:351)
        at android.app.ActivityThread.main(ActivityThread.java:8355)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "app.lawnchair.lawnicons.LawniconsApplication" on path: DexPathList[[zip file "/data/app/~~xWIHus-tAqgf2eC01b73sw==/app.lawnchair.lawnicons-YVk_ID21uazr0ylO68WanQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~xWIHus-tAqgf2eC01b73sw==/app.lawnchair.lawnicons-YVk_ID21uazr0ylO68WanQ==/lib/arm64, /system/lib64, /system_ext/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateApplication(AppComponentFactory.java:76)
        at androidx.core.app.CoreComponentFactory.instantiateApplication(CoreComponentFactory.java:52)
        at android.app.Instrumentation.newApplication(Instrumentation.java:1251)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1505)
        at android.app.LoadedApk.makeApplicationInner(LoadedApk.java:1437) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7161) 
        at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2288) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loopOnce(Looper.java:240) 
        at android.os.Looper.loop(Looper.java:351) 
        at android.app.ActivityThread.main(ActivityThread.java:8355) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:584) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013) 
    	Suppressed: java.lang.NoClassDefFoundError: Failed resolution of: Lapp/lawnchair/lawnicons/Hilt_LawniconsApplication;
        at java.lang.VMClassLoader.findLoadedClass(Native Method)
        at java.lang.ClassLoader.findLoadedClass(ClassLoader.java:738)
```

The line for `homeworker.svg`:
`<item component="ComponentInfo{info.xolf.homeworker/info.xolf.homeworker.MainActivity}" drawable="homeworker" />`

**Comment by badlydrawnface** [comment]
Yeah, i am getting the same thing myself.

Deleting the file causes the compilation to fail, and deleting all of the entries in the file (for some reason), successfully compiles the app, but with no icons, even while working on a version of the repo completely up to date with the master branch.

**Comment by dercodeling** [comment]
@badlydrawnface Are you able to open the Lawnicons app after it's built or does it crash like it does for me? Because, as I've said, for me it installs but I can't open it, because of the ClassNotFoundException.

@naveenccmsd You largely managed the transition away from `grayscale_icon_map.xml`, right? Do you have any idea why having these remaining lines in `grayscale_icon_map.xml` without the corresponding drawables doesn't prevent you from building? Because as I've said, it is more of a mystery to me why y'all are _not_ getting any exception during build.

All of that being said, I might also try opening a PR after all just to see whether it would run for others. And once again, if there is anything I can try or anything you need to know in order to be able to understand my problem, do please ask.

**Comment by naveenccmsd** [comment]
To resolve resource file missing issue , run sub module svg-proceasor before creating apk build.
https://github.com/LawnchairLauncher/lawnicons/blob/develop/.github/workflows/build_debug_apk.yml#L53

It will create all the vector files from svg and create other XML files like drawlbke.xml and appfilter.xml...

**Comment by naveenccmsd** [comment]
About Other issue while opening dex file / java.lang.ClassNotFoundException. Even today I'm getting same exception in my machine but same exception not appearing on some other machine after this version bump 
https://github.com/LawnchairLauncher/lawnicons/pull/830

 As a workaround I always use 1.17 version in my local and won't push the changes to remote. May be you try the same.

**Comment by dercodeling** [comment]
@naveenccmsd Thanks for that info, could you explain how I can run svg-processor? Also, do I have to run this manually before every build?

**Comment by dercodeling** [comment]
@naveenccmsd  Ok so using your advice I successfully fixed the Resource Linking problem, did have to comment out line 15 from `grayscale_icon_map.xml`, though, as there is no svg for `fxxxs_given` (and as it seems there never has been). Thanks for that!

I've gotten a weird error, though, after changing `version` from `1.19` to `1.17` in `build.gradle.kts`, which I don't understand. Do you have any idea what the problem could be? 
Output:

```
\lawnicons\app\build\generated\source\napt_trigger\main\main\app\NaptTrigger.java:3: error: duplicate class: main.app.NaptTrigger
class NaptTrigger {}
^
1 error

[...]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileAppDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
> Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':app:compileAppDebugJavaWithJavac'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
	at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
	at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
	at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
	at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:116)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.executeWithServices(DefaultTaskExecutionGraph.java:136)
	at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph.execute(DefaultTaskExecutionGraph.java:121)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:35)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:51)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:54)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor$ExecuteTasks.call(BuildOperationFiringBuildWorkerExecutor.java:43)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
	at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
	at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
	at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
	at org.gradle.execution.BuildOperationFiringBuildWorkerExecutor.execute(BuildOperationFiringBuildWorkerExecutor.java:40)
	at org.gradle.internal.build.DefaultBuildLifecycleController.lambda$executeTasks$7(DefaultBuildLifecycleController.java:172)
	at org.gradle.internal.model.StateTransitionController.doTransition(StateTransitionController.java:258)
	at org.gradle.internal.model.StateTransitionController.lambda$tryTransition$8(StateTransitionController.java:185)
	at org.gradle.internal.work.DefaultSynchronizer.withLock(DefaultSynchronizer.java:44)
	at org.gradle.internal.model.StateTransitionController.tryTransition(StateTransitionController.java:185)
	at org.gradle.internal.build.DefaultBuildLifecycleController.executeTasks(DefaultBuildLifecycleController.java:172)
	at org.gradle.internal.build.DefaultBuildWorkGraphController$DefaultBuildWorkGraph.runWork(DefaultBuildWorkGraphController.java:209)
	at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:249)
	at org.gradle.internal.work.DefaultWorkerLeaseService.runAsWorkerThread(DefaultWorkerLeaseService.java:109)
	at org.gradle.composite.internal.DefaultBuildController.doRun(DefaultBuildController.java:172)
	at org.gradle.composite.internal.DefaultBuildController.access$000(DefaultBuildController.java:47)
	at org.gradle.composite.internal.DefaultBuildController$BuildOpRunnable.run(DefaultBuildController.java:191)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
Caused by: org.gradle.api.internal.tasks.compile.CompilationFailedException: Compilation failed; see the compiler error output for details.
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:58)
	at org.gradle.api.internal.tasks.compile.JdkJavaCompiler.execute(JdkJavaCompiler.java:41)
	at org.gradle.api.internal.tasks.compile.daemon.AbstractIsolatedCompilerWorkerExecutor$CompilerWorkAction.execute(AbstractIsolatedCompilerWorkerExecutor.java:78)
	at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
	at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)
	at org.gradle.internal.classloader.ClassLoaderUtils.executeInClassloader(ClassLoaderUtils.java:100)
	at org.gradle.workers.internal.AbstractClassLoaderWorker.executeInClassLoader(AbstractClassLoaderWorker.java:43)
	at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:32)
	at org.gradle.workers.internal.FlatClassLoaderWorker.run(FlatClassLoaderWorker.java:22)
	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:87)
	at org.gradle.workers.internal.WorkerDaemonServer.run(WorkerDaemonServer.java:56)
	at org.gradle.process.internal.worker.request.WorkerAction$1.call(WorkerAction.java:138)
	at org.gradle.process.internal.worker.child.WorkerLogEventListener.withWorkerLoggingProtocol(WorkerLogEventListener.java:41)
	at org.gradle.process.internal.worker.request.WorkerAction.run(WorkerAction.java:135)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:182)
	at org.gradle.internal.remote.internal.hub.MessageHubBackedObjectConnection$DispatchWrapper.dispatch(MessageHubBackedObjectConnection.java:164)
	at org.gradle.internal.remote.internal.hub.MessageHub$Handler.run(MessageHub.java:414)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:49)
```

**Comment by naveenccmsd** [comment]
Just delete NaptTrigger.java file which was created by napt plugin

**Comment by dercodeling** [comment]
@naveenccmsd That worked, thank you so much! Finally able to work on new icons again!
