### ISSUE TITLE
Adding icons via icontool doesn't update appfilter.xml

### ISSUE THREAD

**Issue by x9136** [LawnchairLauncher/lawnicons#1246]
### About this discussion

Lately icontool.py has been giving me an error. The result is that the svg is added, but the appfilter.xml file isn't changed.

**Terminal**
```
otttis@Glebs-MacBook-Pro lawnicons % python3 icontool.py add /Users/otttis/Desktop/export/localsend org.localsend.localsend_app/org.localsend.localsend_app.MainActivity "LocalSend"

note: ensure that your icon follows the lawnicons guidelines found in CONTRIBUTING.md
Traceback (most recent call last):
  File "/Users/otttis/Documents/GitHub/lawnicons/icontool.py", line 237, in <module>
    add_parser(args)
  File "/Users/otttis/Documents/GitHub/lawnicons/icontool.py", line 138, in add_parser
    parse_component(False, args.svg, args.component, args.name, args.message)
  File "/Users/otttis/Documents/GitHub/lawnicons/icontool.py", line 101, in parse_component
    sortedxmldata[:52] + calendarstuff[0] +
                         ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```
Any idea how to fix this?

**Comment by SuperDragonXD** [comment]
Fixed in https://github.com/LawnchairLauncher/lawnicons/commit/f98328a9d1157c32b5c9e0dded3652558c34d5f5.
