### ISSUE TITLE
ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType

### ISSUE THREAD

**Issue by Goooler** [LawnchairLauncher/lawnicons#1383]
### About this discussion

Deobufucated:

```
app.lawnchair.lawnicons E    FATAL EXCEPTION: DefaultDispatcher-worker-1
Process: app.lawnchair.lawnicons, PID: 5577
java.lang.RuntimeException: Missing type parameter.
    at com.google.gson.reflect.TypeToken.com.google.gson.reflect.TypeToken.getSuperclassTypeParameter(SourceFile:3) <init>
    at app.lawnchair.lawnicons.repository.OssLibraryRepository$ossLibraries$1$listType$1.<init>(Unknown Source:0)
    at app.lawnchair.lawnicons.repository.OssLibraryRepository$ossLibraries$1.invokeSuspend(Unknown Source:109)
    at app.lawnchair.lawnicons.repository.OssLibraryRepository$ossLibraries$1.app.lawnchair.lawnicons.repository.OssLibraryRepository$ossLibraries$1.invoke(Unknown Source:12)
    at kotlinx.coroutines.flow.SafeFlow.collectSafely(Unknown Source:2)
    at kotlinx.coroutines.flow.AbstractFlow.collect(Unknown Source:67)
    at kotlinx.coroutines.flow.FlowKt__ShareKt$launchSharing$1.k(Unknown Source:94)
    at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(Unknown Source:8)
    at kotlinx.coroutines.DispatchedTask.run(Unknown Source:111)
    at kotlinx.coroutines.internal.LimitedDispatcher$Worker.run(Unknown Source:3)
    at kotlinx.coroutines.scheduling.TaskImpl.run(Unknown Source:2)
    at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(Unknown Source:62)
```

Something related to Gson in #1288, will happen after enabling R8 fullMode.

**Comment by Goooler** [comment]
```
2023-08-17 09:37:32.721 20924-20924 ContributorsViewModel   app.lawnchair.lawnicons              E  Failed to load contributors (Ask Studio Bot)
java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
    at N2.z.c(Unknown Source:44)
    at N2.j0.c(Unknown Source:24)
    at N2.h0.invoke(Unknown Source:35)
    at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
    at $Proxy6.a(Unknown Source)
    at b1.b.a(Unknown Source:54)
    at app.lawnchair.lawnicons.viewmodel.b.l(Unknown Source:36)
    at S1.a.z(Unknown Source:8)
    at o2.a.p(Unknown Source:141)
    at B.a.k2(Unknown Source:11)
    at j2.a.r0(Unknown Source:77)
    at j2.B.C(Unknown Source:24)
    at j2.B.D(Unknown Source:11)
    at app.lawnchair.lawnicons.viewmodel.ContributorsViewModel.<init>(Unknown Source:78)
    at Y0.j.get(Unknown Source:45)
    at H1.f.e(Unknown Source:41)
    at androidx.lifecycle.a.b(Unknown Source:25)
    at H1.i.b(Unknown Source:14)
    at Z.E.c(Unknown Source:62)
    at Z.E.b(Unknown Source:12)
    at B.a.g1(Unknown Source:42)
    at B.a.E2(Unknown Source:23)
    at h1.j.f(Unknown Source:46)
    at c1.j.a(Unknown Source:145)
    at c1.j.h0(Unknown Source:79)
    at M.f.b(Unknown Source:50)
    at M.f.h0(Unknown Source:8)
    at androidx.navigation.compose.m.a(Unknown Source:86)
    at androidx.navigation.compose.m.r0(Unknown Source:28)
    at M.f.r0(Unknown Source:58)
    at F.L.a(Unknown Source:29)
    at N.o.d(Unknown Source:118)
    at androidx.navigation.compose.q.f(Unknown Source:58)
    at androidx.navigation.compose.t.a(Unknown Source:55)
    at androidx.navigation.compose.t.r0(Unknown Source:28)
    at M.f.r0(Unknown Source:58)
    at F.L.a(Unknown Source:29)
    at androidx.navigation.compose.q.b(Unknown Source:47)
    at androidx.navigation.compose.B.h0(Unknown Source:101)
    at M.f.b(Unknown Source:50)
    at M.f.h0(Unknown Source:8)
    at m.j.n0(Unknown Source:125)
    at M.f.a(Unknown Source:50)
    at M.f.n0(Unknown Source:8)
    at m.n.b(Unknown Source:570)
    at m.n.c(Unknown Source:339)
    at m.k.a(Unknown Source:270)
    at m.k.r0(Unknown Source:16)
    at M.f.r0(Unknown Source:58)
    at m.n.a(Unknown Source:879)
    at androidx.navigation.compose.q.c(Unknown Source:548)
    at androidx.navigation.compose.C.a(Unknown Source:80)
    at androidx.navigation.compose.C.r0(Unknown Source:28)
    at F.U0.g(Unknown Source:14)
    at F.J.s0(Unknown Source:188)
    at F.J.I(Unknown Source:219)
    at F.J.q0(Unknown Source:32)
    at F.Q.B(Unknown Source:18)
    at F.d1.F(Unknown Source:84)
    at F.b1.C0(Unknown Source:403)
    at androidx.compose.ui.platform.e0.doFrame(Unknown Source:6)
    at androidx.compose.ui.platform.d0.X(Unknown Source:33)
    at androidx.compose.ui.platform.c0.doFrame(Unknown Source:12)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1229)
    at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
    at android.view.Choreographer.doCallbacks(Choreographer.java:899)
    at android.view.Choreographer.doFrame(Choreographer.java:827)
    at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
    at android.os.Handler.handleCallback(Handler.java:984)
    at android.os.Handler.dispatchMessage(Handler.java:104)
    at android.os.Looper.loopOnce(Looper.java:238)
    at android.os.Looper.loop(Looper.java:357)
    at android.app.ActivityThread.main(ActivityThread.java:8118)
    at java.lang.reflect.Method.invoke(Native Method)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:957)
```
