### ISSUE TITLE
App crash while using search

### ISSUE THREAD

**Issue by mwchiao** [LawnchairLauncher/lawnicons#2258]
### About this discussion

I am getting app crashes when using the search in the app. In particular when searching for mapped components on the default camera icon.

Version: 2.11.0
Steps to reproduce:
1. Go to search in app
2. Check "Component name" filter/option
3. Search for "gcam92"
4. App crashes

I've tried different strings and haven't nailed down a specific pattern that makes it crash. But here is an example log I get the rare times I do get a crash/error dialog

```
type: crash
osVersion: google/panther/panther:14/AP2A.240805.005/2024080600:user/release-keys
package: app.lawnchair.lawnicons:15
process: app.lawnchair.lawnicons
processUptime: 18599 + 236 ms
installer: com.looker.droidify

java.lang.IndexOutOfBoundsException: index: 0, size: 0
	at u3.k.x(Unknown Source:15)
	at P2.j.get(Unknown Source:4)
	at I2.a.K(Unknown Source:126)
	at N1.x.k(Unknown Source:260)
	at U.a.b(Unknown Source:43)
	at U.a.k(Unknown Source:8)
	at D.G.l(Unknown Source:261)
	at U.a.l(Unknown Source:51)
	at e2.c.e(Unknown Source:690)
	at e2.c.d(Unknown Source:186)
	at I2.a.N(Unknown Source:589)
	at N1.q.l(Unknown Source:111)
	at U.a.l(Unknown Source:51)
	at M.q.G(Unknown Source:437)
	at M.q.P(Unknown Source:28)
	at u3.k.m(Unknown Source:293)
	at u3.k.n(Unknown Source:78)
	at I2.a.M(Unknown Source:347)
	at I2.a.J(Unknown Source:171)
	at P1.q.l(Unknown Source:179)
	at U.a.l(Unknown Source:51)
	at M.q.G(Unknown Source:437)
	at M.q.N(Unknown Source:136)
	at M.q.p(Unknown Source:243)
	at M.q.E(Unknown Source:31)
	at M.v.w(Unknown Source:22)
	at M.z0.q(Unknown Source:107)
	at M.x0.p(Unknown Source:539)
	at M.D.doFrame(Unknown Source:13)
	at y0.U.doFrame(Unknown Source:47)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1404)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1415)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1015)
	at android.view.Choreographer.doFrame(Choreographer.java:941)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1389)
	at android.os.Handler.handleCallback(Handler.java:959)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
	Suppressed: W2.f: [M.l0@f916283, y0.w0@13d0c00, p0{Cancelling}@8a64c39, V@71e027e]
```

**Comment by SuperDragonXD** [comment]
Thanks for making this issue. I plan on fixing this as soon as possible, but might take a few more days.

**Comment by SuperDragonXD** [comment]
Re-opening this issue with a label, until we release Lawnicons 2.12.0
